<a href="https://colab.research.google.com/github/Naushad9458/CS224N/blob/main/softmax_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
y=np.array([0,1,2,2])

In [5]:
y # 4 samples and 3 classes

array([0, 1, 2, 2])

In [6]:
#one-hot encoding to samples
y_enc = (np.arange(np.max(y) + 1) == y[:, None]).astype(float)

print('one-hot encoding:\n', y_enc)

one-hot encoding:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [7]:
X = np.array([[0.1, 0.5],
              [1.1, 2.3],
              [-1.1, -2.3],
              [-1.5, -2.5]])

W = np.array([[0.1, 0.2, 0.3],
              [0.1, 0.2, 0.3]])

bias = np.array([0.01, 0.1, 0.1])

print('Inputs X:\n', X)
print('\nWeights W:\n', W)
print('\nbias:\n', bias)

Inputs X:
 [[ 0.1  0.5]
 [ 1.1  2.3]
 [-1.1 -2.3]
 [-1.5 -2.5]]

Weights W:
 [[0.1 0.2 0.3]
 [0.1 0.2 0.3]]

bias:
 [0.01 0.1  0.1 ]


In [8]:
def net_input(X, W, b):
    return (X.dot(W) + b)

In [9]:
net_in = net_input(X, W, bias)
print('net input:\n', net_in)

net input:
 [[ 0.07  0.22  0.28]
 [ 0.35  0.78  1.12]
 [-0.33 -0.58 -0.92]
 [-0.39 -0.7  -1.1 ]]


In [12]:
np.exp(net_in.T)

array([[1.07250818, 1.41906755, 0.71892373, 0.67705687],
       [1.24607673, 2.18147227, 0.55989837, 0.4965853 ],
       [1.32312981, 3.0648542 , 0.39851904, 0.33287108]])

In [13]:
np.sum(np.exp(net_in), axis=1)

array([3.64171472, 6.66539402, 1.67734114, 1.50651326])

In [14]:
np.exp(net_in.T)/np.sum(np.exp(net_in), axis=1)

array([[0.29450637, 0.21290077, 0.42860913, 0.44941979],
       [0.34216758, 0.32728332, 0.33380113, 0.32962558],
       [0.36332605, 0.45981591, 0.23758974, 0.22095463]])

In [15]:
def softmax(z):
    return (np.exp(z.T) / np.sum(np.exp(z), axis=1)).T

In [16]:
smax = softmax(net_in)
print('softmax:\n', smax)

softmax:
 [[0.29450637 0.34216758 0.36332605]
 [0.21290077 0.32728332 0.45981591]
 [0.42860913 0.33380113 0.23758974]
 [0.44941979 0.32962558 0.22095463]]


In [17]:
def to_classlabel(z):
    return z.argmax(axis=1)

print('predicted class labels: ', to_classlabel(smax))

predicted class labels:  [2 2 0 0]


In [18]:
def cross_entropy(output, y_target):
    return - np.sum(np.log(output) * (y_target), axis=1)

In [19]:
xent = cross_entropy(smax, y_enc)
print('Cross Entropy:', xent)

Cross Entropy: [1.22245465 1.11692907 1.43720989 1.50979788]


In [20]:
def cost(output, y_target):
    return np.mean(cross_entropy(output, y_target))

J_cost = cost(smax, y_enc)
print('Cost: ', J_cost)

Cost:  1.3215978715930938


In [21]:
!pip install mlxtend

In [22]:
from mlxtend.data import iris_data
from mlxtend.plotting import plot_decision_regions
from mlxtend.classifier import SoftmaxRegression
import matplotlib.pyplot as plt

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
